-- auto Generated on 2020-04-09
-- DROP TABLE IF EXISTS book;
CREATE TABLE book(
	id VARCHAR (50) NOT NULL COMMENT 'id',
	book_name VARCHAR (50) DEFAULT '' COMMENT '图书名称',
	book_price DOUBLE (16,4) DEFAULT 0.0 COMMENT '图书价格',
	create_by VARCHAR (50) DEFAULT '' COMMENT '创建人id',
	create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	update_by VARCHAR (50) DEFAULT '' COMMENT '更新人id',
	update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'book';
